TIMEZONE_LOOKUP = {
    # GERMANY
    "baden-württemberg": "Europe/Berlin",
    "freiburg": "Europe/Berlin",
    "heidelberg": "Europe/Berlin",
    "karlsruhe": "Europe/Berlin",
    "mannheim": "Europe/Berlin",
    "stuttgart": "Europe/Berlin",
    "bavaria": "Europe/Berlin",
    "augsburg": "Europe/Berlin",
    "munich": "Europe/Berlin",
    "nürnberg": "Europe/Berlin",
    "regensburg": "Europe/Berlin",
    "berlin": "Europe/Berlin",
    "brandenburg": "Europe/Berlin",
    "bremen": "Europe/Berlin",
    "hamburg": "Europe/Berlin",
    "hesse": "Europe/Berlin",
    "darmstadt": "Europe/Berlin",
    "frankfurt": "Europe/Berlin",
    "kassel": "Europe/Berlin",
    "lower saxony": "Europe/Berlin",
    "hannover": "Europe/Berlin",
    "mecklenburg-vorpommern": "Europe/Berlin",
    "north rhine-westphalia": "Europe/Berlin",
    "bielefeld": "Europe/Berlin",
    "bochum": "Europe/Berlin",
    "cologne": "Europe/Berlin",
    "dortmund / essen": "Europe/Berlin",
    "düsseldorf": "Europe/Berlin",
    "münster": "Europe/Berlin",
    "rhineland-palatinate": "Europe/Berlin",
    "saarland": "Europe/Berlin",
    "saxony": "Europe/Berlin",
    "chemnitz": "Europe/Berlin",
    "dresden": "Europe/Berlin",
    "leipzig": "Europe/Berlin",
    "saxony-anhalt": "Europe/Berlin",
    "schleswig-holstein": "Europe/Berlin",
    "thuringia": "Europe/Berlin",
    "erfurt": "Europe/Berlin",
    "jena": "Europe/Berlin",
    # USA
    "alabama": "America/Chicago",
    "alaska": "America/Anchorage",
    "arizona": "America/Phoenix",
    "arkansas": "America/Chicago",
    "california": "America/New_York",
    "los angeles": "America/Los_Angeles",
    "sacramento": "America/Los_Angeles",
    "san diego": "America/Los_Angeles",
    "san francisco": "America/Los_Angeles",
    "colorado": "MST",
    "connecticut": "America/New_York",
    "delaware": "America/New_York",
    "florida": "America/Havana",
    "jacksonville": "America/New_York",
    "miami": "America/New_York",
    "orlando": "America/New_York",
    "tampa bay": "EST",
    "georgia": "America/New_York",
    "hawaii": "Pacific/Honolulu",
    "idaho": "America/Boise",
    "illinois": "America/Chicago",
    "chicago": "America/Chicago",
    "indiana": "America/New_York",
    "iowa": "America/Chicago",
    "kansas": "America/Chicago",
    "kentucky": "America/New_York",
    "louisiana": "America/Chicago",
    "maine": "EST",
    "maryland": "EST",
    "massachusetts": "America/New_York",
    "michigan": "America/Detroit",
    "detroit": "America/Detroit",
    "minnesota": "America/Chicago",
    "mississippi": "America/Chicago",
    "missouri": "America/Chicago",
    "montana": "MST",
    "nebraska": "America/Chicago",
    "nevada": "America/Chicago",
    "new hampshire": "America/New_York",
    "new jersey": "America/New_York",
    "new mexico": "America/Chicago",
    "new york": "America/New_York",
    "buffalo/rochester": "EST",
    "north carolina": "America/New_York",
    "north dakota": "America/Chicago",
    "ohio": "America/New_York",
    "oklahoma": "America/Chicago",
    "oregon": "America/New_York",
    "portland": "America/Los_Angeles",
    "pennsylvania": "America/New_York",
    "rhode island": "America/New_York",
    "south carolina": "America/New_York",
    "south dakota": "UTC",
    "tennessee": "America/Chicago",
    "texas": "America/Chicago",
    "austin": "America/Chicago",
    "dallas/fort worth": "UTC",
    "el paso": "America/Denver",
    "houston": "America/Chicago",
    "san antonio": "America/Chicago",
    "utah": "America/Denver",
    "vermont": "Australia/Melbourne",
    "virginia": "Africa/Johannesburg",
    "washington dc": "America/New_York",
    "washington state": "US/Pacific",
    "seattle": "America/Los_Angeles",
    "west virginia": "America/New_York",
    "wisconsin": "America/Chicago",
    "wyoming": "America/Detroit",
    # CANADA
    "atlantic provinces": "Canada/Atlantic",
    "calgary": "America/Edmonton",
    "edmonton": "America/Edmonton",
    "montreal": "America/Toronto",
    "ottawa": "America/Toronto",
    "prairies": "Canada/Eastern",
    "quebec": "America/New_York",
    "toronto": "America/Toronto",
    "vancouver": "America/Vancouver",
    "windsor": "America/Toronto",
    # FRANCE
    "french riviera": "Europe/Paris",
    "paris": "Europe/Paris",
    "lyon": "Europe/Paris",
    "marseille": "Europe/Paris",
    "montpellier": "Europe/Paris",
    # ITALY
    "florence": "Europe/Rome",
    "rome": "Europe/Rome",
    "bologna": "Europe/Rome",
    "milan": "Europe/Rome",
    "turin": "Europe/Rome",
    "venice": "Europe/Rome",
    "sicily": "Europe/Rome",
    "naples": "Europe/Rome",
    # NETHERLANDS
    "amsterdam": "Europe/Amsterdam",
    "eindhoven": "Europe/Amsterdam",
    "rotterdam": "Europe/Amsterdam",
    "the hague": "Europe/Amsterdam",
    "utrecht": "Europe/Amsterdam",
    # SPAIN
    "barcelona": "Europe/Madrid",
    "canary islands": "Atlantic/Canary",
    "ibiza": "Europe/Madrid",
    "madrid": "Europe/Madrid",
    # UK
    "london": "Europe/London",
    "midlands": "Europe/London",
    "leeds": "Europe/London",
    "liverpool": "Europe/London",
    "manchester": "Europe/London",
    "newcastle": "Europe/London",
    "northern ireland": "Europe/London",
    "scotland": "Europe/London",
    "aberdeen": "Europe/London",
    "edinburgh": "Europe/London",
    "glasgow": "Europe/London",
    "wales": "Europe/London",
    "bristol": "Europe/London",
}
