TIMEZONE_LOOKUP = {
    "baden-württemberg": "Europe/Berlin",
    "freiburg": "Europe/Berlin",
    "heidelberg": "Europe/Berlin",
    "karlsruhe": "Europe/Berlin",
    "mannheim": "Europe/Berlin",
    "stuttgart": "Europe/Berlin",
    "bavaria": "Europe/Berlin",
    "augsburg": "Europe/Berlin",
    "munich": "Europe/Berlin",
    "nürnberg": "Europe/Berlin",
    "regensburg": "Europe/Berlin",
    "berlin": "Europe/Berlin",
    "brandenburg": "Europe/Berlin",
    "bremen": "Europe/Berlin",
    "hamburg": "Europe/Berlin",
    "hesse": "Europe/Berlin",
    "darmstadt": "Europe/Berlin",
    "frankfurt": "Europe/Berlin",
    "kassel": "Europe/Berlin",
    "lower saxony": "Europe/Berlin",
    "hannover": "Europe/Berlin",
    "mecklenburg-vorpommern": "Europe/Berlin",
    "north rhine-westphalia": "Europe/Berlin",
    "bielefeld": "Europe/Berlin",
    "bochum": "Europe/Berlin",
    "cologne": "Europe/Berlin",
    "dortmund / essen": "Europe/Berlin",
    "düsseldorf": "Europe/Berlin",
    "münster": "Europe/Berlin",
    "rhineland-palatinate": "Europe/Berlin",
    "saarland": "Europe/Berlin",
    "saxony": "Europe/Berlin",
    "chemnitz": "Europe/Berlin",
    "dresden": "Europe/Berlin",
    "leipzig": "Europe/Berlin",
    "saxony-anhalt": "Europe/Berlin",
    "schleswig-holstein": "Europe/Berlin",
    "thuringia": "Europe/Berlin",
    "erfurt": "Europe/Berlin",
    "jena": "Europe/Berlin",
    "san francisco": "America/Los_Angeles",
    "los angeles": "America/Los_Angeles",
    "new york": "America/New_York",
    "boston": "America/New_York",
    "chicago": "America/Chicago",
}
